sudo: required

language: minimal

services:
  docker

before_script:
  - docker build -t dpyro/syslog-relay .
  - docker swarm init
  - docker stack deploy -c docker-compose.test.yml test

script:
  - sleep 10
  - docker run --rm buildpack-deps logger -n localhost -P 514 -p local0.debug -t test -sT "Foobar McBarfoo"
  - sleep 10
  - docker service logs test_relay 2>&1 | grep "Foobar McBarfoo" /dev/stdin
  - docker service logs test_sink 2>&1 | grep "Foobar McBarfoo" /dev/stdin

after_failure:
  - docker service logs test_relay
  - docker service logs test_sink

after_script:
  - docker stack rm test
