sudo: required

language: minimal

services:
  docker

before_script:
  - docker-compose -f docker-compose.yml config --quiet

script:
  - docker-compose -f docker-compose.yml up --build --detach
  - sleep 30
  - docker-compose -f docker-compose.yml logs --no-color | grep "^relay" | grep "File Output" /dev/stdin
  - docker-compose -f docker-compose.yml logs --no-color | grep "^sink"  | grep "File Output" /dev/stdin
  - docker-compose -f docker-compose.yml logs --no-color | grep "^relay" | grep "Network Output" /dev/stdin
  - docker-compose -f docker-compose.yml logs --no-color | grep "^sink"  | grep "Network Output" /dev/stdin

after_failure:
  - docker-compose logs

after_script:
  - docker-compose down
