sudo: required

language: minimal

services:
  docker

env:
  - DOCKER_COMPOSE_VERSION=17.12.0

before_script:
  # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  - docker-compose config --quiet

script:
  - /bin/sh -c 'docker-compose up --build --detach'
  - sleep 30
  - docker-compose logs --no-color | grep "^relay" | grep "File Output" /dev/stdin
  - docker-compose logs --no-color | grep "^sink"  | grep "File Output" /dev/stdin
  - docker-compose logs --no-color | grep "^relay" | grep "Network Output" /dev/stdin
  - docker-compose logs --no-color | grep "^sink"  | grep "Network Output" /dev/stdin

after_failure:
  - docker-compose logs

after_script:
  - docker-compose down
