# Use for testing
version: "3.0"

services:
  relay:
    image: dpyro/syslog-relay
    environment:
      RELAY_TARGET: "@@sink:514"
    ports:
      - "514:514/tcp"

  sink:
    image: dpyro/syslog-relay
    environment:
      RELAY_TARGET: "@nowhere"

  logger:
    image: buildpack-deps
    command: logger -n relay -P 514 -p local0.debug -t test -sT "Foobar McBarfoo"
    deploy:
      restart_policy:
        delay: 5s
