#!/usr/bin/env bash

usage() {
  echo >&2 "Usage: $0 syslog_target"
  exit 1
}

generate_script() {
	local script_stdout=''
	local script_target=''

  if [ -z "$QUIET" ]; then
    script_stdout=$(cat <<-EOF
			action(type="omstdout")
		EOF
		)
  fi

  if [ -n "$SYSLOG_TARGET" ]; then
    script_target=$(cat <<-EOF
			\$WorkDirectory /var/spool/rsyslog
			\$ActionQueueType LinkedList   			# use asynchronous processing
			\$ActionQueueFileName srvrfwd  			# set file name, also enables disk mode
			\$ActionResumeRetryCount 1     			# retries on insert failure
			\$ActionQueueSaveOnShutdown on 			# save in-memory data if rsyslog shuts down
			*.* $SYSLOG_TARGET
		EOF
		)
  fi

  printf '%s\n\n%s' "$script_stdout" "$script_target"
}

export SYSLOG_TARGET=''
export QUIET=''

while getopts 'h?q' c
do
  case $c in
    q) QUIET=true ;;
    h|?|*) usage ;;
  esac
done
# Drop option args
shift "$((OPTIND-1))"

SYSLOG_TARGET=$1
shift

if [ "$1" = "--" ]; then
  shift
fi

# Create the autogenerated script
generate_script > /root/script.conf

exec rsyslogd -n "$@"